spring:
  datasource:
    url: jdbc:h2:file:./data/pingu
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  servlet:
    context-path: /api