spring:
  cache:
    type: none
  datasource:
    url: jdbc:h2:file:./data/pingu
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        # Because keywords like "user" are reserved in H2
        globally_quoted_identifiers: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 100MB


server:
  servlet:
    context-path: /api